# Project: ????????
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o student.o course.o selection.o studentlist.o courselist.o selectionlist.o
LINKOBJ  = main.o student.o course.o selection.o studentlist.o courselist.o selectionlist.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 学生选课系统.exe
CXXFLAGS = $(CXXINCS) -std=c++14
CFLAGS   = $(INCS) -std=c++14
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

student.o: student.cpp
	$(CPP) -c student.cpp -o student.o $(CXXFLAGS)

course.o: course.cpp
	$(CPP) -c course.cpp -o course.o $(CXXFLAGS)

selection.o: selection.cpp
	$(CPP) -c selection.cpp -o selection.o $(CXXFLAGS)

studentlist.o: studentlist.cpp
	$(CPP) -c studentlist.cpp -o studentlist.o $(CXXFLAGS)

courselist.o: courselist.cpp
	$(CPP) -c courselist.cpp -o courselist.o $(CXXFLAGS)

selectionlist.o: selectionlist.cpp
	$(CPP) -c selectionlist.cpp -o selectionlist.o $(CXXFLAGS)
